services:
    zikula_atom_theme.twig.atomtheme_extension:
        class: Zikula\AtomTheme\Twig\AtomThemeExtension
        arguments:
          - "@zikula_extensions_module.api.variable"
          - "@request_stack"
        tags:
            - { name: twig.extension }
