engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
        php:
  eslint:
    enabled: true
    checks:
      no-alert:
        enabled: false
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - HACK
      - TODO
  markdownlint:
    enabled: true
  phan:
    enabled: true
    config:
      ignore-undeclared: true
      dead-code-detection: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true

ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.md"
  - "**.php"

exclude_paths:
- "src/lib/legacy/"
- "src/javascript/jquery-plugins/"
- "src/javascript/plugins/"
- "src/javascript/underscore/"
- "*.min.js"
- "**/tests/"
- "**/vendor/"
