preset: symfony

enabled:
  - short_array_syntax

disabled:
  - concat_without_spaces
  - no_empty_lines_after_phpdocs
  - multiline_array_trailing_comma
  - php_unit_fqcn_annotation
  - phpdoc_align
  - phpdoc_no_empty_return
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_summary
  - phpdoc_to_comment
  - phpdoc_type_to_var
  - pre_increment
  - single_quote
  - spaces_cast
  - unalign_double_arrow
  - unalign_equals
  - empty_return

finder:
  exclude:
    - "src/javascript"
    - "src/lib/legacy/idn"
    - "tools"
    - "src/system/RoutesModule"
