## YAML Override template
## original/file.tpl: override/file.tpl
---
system/Zikula/Module/SearchModule/Resources/views/Block/search.tpl: themes/Zikula/Theme/Andreas08Theme/Resources/views/modules/ZikulaSearchModule/Block/search.tpl
system/Zikula/Module/BlocksModule/Resources/views/Block/Extmenu/topnav.tpl: themes/Zikula/Theme/Andreas08Theme/Resources/views/modules/ZikulaBlocksModule/Block/Extmenu/topnav.tpl