parameters:
    installed:        false
    env:              prod
    debug:            false
    compat_layer:     true
    script_position:  head
    # script_position defines the location where javascripts will be placed in the page
    # choices are `head` or `foot`
    # in Core-1.x this defaults to `head`. In Core-2.0 it will default to `foot`
    # it can be changed to `foot` now if you are certain your site's inline javascript is compatible.
    temp_dir:         %kernel.cache_dir%/ztemp
    datadir:          userdata
    system.chmod_dir: 0777

    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     ~
    database_user:     ~
    database_password: ~
    database_path:     ~
    database_socket:   ~
    database_server_version: 5
    # _actual_ server version doesn't matter here. Any value compensates for Doctrine Bug DBAL-1057
    # see http://www.doctrine-project.org/jira/browse/DBAL-1057
    # the actual value is written on install

    pagerendertime:    false

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
    url_secret:        ~

    zikula.session.name: _zsid
