core:
    resource: "@CoreBundle/Resources/config/routing.xml"

hook:
    resource: "@ZikulaHookBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

installer:
    resource: "@ZikulaCoreInstallerBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

Routing:
    resource: .
    type: zikularoutesmodule
