name: Copy Files to Distribution
on:
  push:
    branches: [master]
jobs:
  copy_kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Kernel.php
        uses: andstor/copycat-action@v2
        with:
          personal_token: ${{ secrets.COPY_DIST_TOKEN }}
          src_path: /src/Kernel.php
          dst_path: /src/Kernel.php
          dst_owner: zikula
          dst_repo_name: distribution
  copy_index:
    runs-on: ubuntu-latest
    steps:
      - name: Copy index.php
        uses: andstor/copycat-action@v2
        with:
          personal_token: ${{ secrets.COPY_DIST_TOKEN }}
          src_path: /public/index.php
          dst_path: /public/index.php
          dst_owner: zikula
          dst_repo_name: distribution
  copy_htaccess:
    runs-on: ubuntu-latest
    steps:
      - name: Copy .htaccess
        uses: andstor/copycat-action@v2
        with:
          personal_token: ${{ secrets.COPY_DIST_TOKEN }}
          src_path: /public/.htaccess
          dst_path: /public/.htaccess
          dst_owner: zikula
          dst_repo_name: distribution
  copy_env:
    runs-on: ubuntu-latest
    steps:
      - name: Copy .env
        uses: andstor/copycat-action@v2
        with:
          personal_token: ${{ secrets.COPY_DIST_TOKEN }}
          src_path: /.env
          dst_path: /.env
          dst_owner: zikula
          dst_repo_name: distribution
  copy_config:
    runs-on: ubuntu-latest
    steps:
      - name: Copy config/*
        uses: andstor/copycat-action@v2
        with:
          personal_token: ${{ secrets.COPY_DIST_TOKEN }}
          src_path: /config/*
          src_filter: 'bootstrap.php|bundles.php|routes.yaml|services.yaml'
          dst_path: /config/
          dst_owner: zikula
          dst_repo_name: distribution
  copy_dynamic:
    runs-on: ubuntu-latest
    steps:
      - name: Copy config/dynamic/default.yaml
        uses: andstor/copycat-action@v2
        with:
          personal_token: ${{ secrets.COPY_DIST_TOKEN }}
          src_path: /config/dynamic/default.yaml
          dst_path: /config/dynamic/default.yaml
          dst_owner: zikula
          dst_repo_name: distribution
  copy_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Copy config/packages/*
        uses: andstor/copycat-action@v2
        with:
          personal_token: ${{ secrets.COPY_DIST_TOKEN }}
          src_path: /config/packages/*
          src_filter: 'bazinga_js_translation.yaml|cache.yaml|doctrine.yaml|framework.yaml|jms_i18n_routing.yaml|liip_imagine.yaml|mailer.yaml|notifier.yaml|php_translation.yaml|routing.yaml|security.yaml|security_checker.yaml|sensio_framework_extra.yaml|stof_doctrine_extensions.yaml|swiftmailer.yaml|translation.yaml|twig.yaml|validator.yaml|workflow.yaml'
          dst_path: /config/packages/
          dst_owner: zikula
          dst_repo_name: distribution
  copy_packages_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Copy config/packages/prod
        uses: andstor/copycat-action@v2
        with:
          personal_token: ${{ secrets.COPY_DIST_TOKEN }}
          src_path: /config/packages/prod/*
          dst_path: /config/packages/prod
          dst_owner: zikula
          dst_repo_name: distribution
  copy_routes:
    runs-on: ubuntu-latest
    steps:
      - name: Copy config/routes
        uses: andstor/copycat-action@v2
        with:
          personal_token: ${{ secrets.COPY_DIST_TOKEN }}
          src_path: /config/routes/*
          src_filter: 'annotations.yaml|fos_js_routing.yaml|js_translation.yaml|liip_imagine.yaml|php_translation.yaml|zikula.yaml'
          dst_path: /config/routes
          dst_owner: zikula
          dst_repo_name: distribution
  copy_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Copy config/workflows
        uses: andstor/copycat-action@v2
        with:
          personal_token: ${{ secrets.COPY_DIST_TOKEN }}
          src_path: /config/workflows/*
          dst_path: /config/workflows
          dst_owner: zikula
          dst_repo_name: distribution
